### ISSUE TITLE
Some insight about PR #11 : diff feature also added

### ISSUE THREAD

**Issue by lalmeras** [gheesh/ansible-ovh-dns#14]
First, thanks for the merge ! (and for this module).

I just want to draw attention on the fact I mistakenly push on the proposed branch another feature that was not described in PR summary. The merged code includes a diff support for the role. Diff is done by dumping before and after dict values as YAML.

I'm fairly confident it is working as I use it to help me to reconciliate an unsynchronized inventory and live state (missing entries, updated live entries, ...). It was not intended to be part of this PR, and I originally think to create a separate PR, but I push it on the wrong branch :-/

If you don't agree with this feature, or think it is not done the right way, feel free to revert 58dd4f16616cd652139e9884f1bf2ef3f5739d64. I'd be glad it fits your needs.

Sorry for the inconvenience.

**Comment by gheesh** [comment]
No worries, but please try to add it as a parameter on the README so it is documented :-)

**Comment by lalmeras** [comment]
PR #16 created.

**Comment by lalmeras** [comment]
This was merged a long time ago.
